const root=document.documentElement,nav=document.querySelector('.site-nav'),menu=document.querySelector('.menu-toggle'),theme=document.querySelector('.theme-toggle');
const AUTH_API_URL='https://script.google.com/macros/s/AKfycbzEusnnkKwrUN7Sp0M7w3wa_YVDxROXkl0w_m1JZWhRwQGicH6d26zKj3eBAU9HpCGlOA/exec';
const saved=localStorage.getItem('blog-theme');if(saved==='dark'||(!saved&&matchMedia('(prefers-color-scheme:dark)').matches))root.dataset.theme='dark';
function themeLabel(){theme?.setAttribute('aria-label',root.dataset.theme==='dark'?'라이트 모드로 변경':'다크 모드로 변경')}themeLabel();
theme?.addEventListener('click',()=>{root.dataset.theme=root.dataset.theme==='dark'?'':'dark';localStorage.setItem('blog-theme',root.dataset.theme||'light');themeLabel()});
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open);document.body.classList.toggle('nav-open',open)});
document.querySelectorAll('.site-nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('nav-open')}));
addEventListener('scroll',()=>document.querySelector('.site-header')?.classList.toggle('scrolled',scrollY>8),{passive:true});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
document.querySelectorAll('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());

function validateForm(form){let valid=true;form.querySelectorAll('[required]').forEach(field=>{const wrap=field.closest('.form-field'),error=wrap?.querySelector('.error-message');let msg='';if(field.type==='checkbox'&&!field.checked)msg='동의가 필요합니다.';else if(!field.value.trim())msg='필수 입력 항목입니다.';else if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value))msg='올바른 이메일 주소를 입력해 주세요.';else if(field.minLength>0&&field.value.length<field.minLength)msg=`${field.minLength}자 이상 입력해 주세요.`;wrap?.classList.toggle('invalid',!!msg);if(error)error.textContent=msg;field.setAttribute('aria-invalid',String(!!msg));if(msg)valid=false});return valid}
document.querySelectorAll('[data-demo-form]:not(.auth-card)').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();const status=form.querySelector('.form-status');if(!validateForm(form)){if(status)status.textContent='입력 내용을 다시 확인해 주세요.';form.querySelector('.invalid input,.invalid textarea')?.focus();return}if(status)status.textContent=form.dataset.success||'완료되었습니다.';form.reset()}));

async function authRequest(action,payload={}){const body=new URLSearchParams({action,...payload});const response=await fetch(AUTH_API_URL,{method:'POST',body,redirect:'follow'});if(!response.ok)throw new Error('인증 서버에 연결할 수 없습니다.');return response.json()}
function authToken(){return sessionStorage.getItem('blog-auth-token')||localStorage.getItem('blog-auth-token')||''}
function saveAuthToken(token,remember){sessionStorage.removeItem('blog-auth-token');localStorage.removeItem('blog-auth-token');(remember?localStorage:sessionStorage).setItem('blog-auth-token',token)}
function clearAuthToken(){sessionStorage.removeItem('blog-auth-token');localStorage.removeItem('blog-auth-token');localStorage.removeItem('blog-auth-user')}

document.querySelectorAll('.auth-card[data-demo-form]').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('.form-status'),button=form.querySelector('[type="submit"]'),isSignup=location.pathname.endsWith('signup.html');if(!validateForm(form)){status.textContent='입력 내용을 다시 확인해 주세요.';form.querySelector('.invalid input,.invalid textarea')?.focus();return}const payload=isSignup?{email:form.querySelector('#email').value,password:form.querySelector('#password').value,name:form.querySelector('#name').value,nickname:form.querySelector('#nickname').value}:{email:form.querySelector('#email').value,password:form.querySelector('#password').value};status.textContent='처리 중입니다...';button.disabled=true;try{const result=await authRequest(isSignup?'signup':'login',payload);if(!result.success)throw new Error(result.message||'요청을 처리하지 못했습니다.');if(isSignup){status.textContent='회원가입이 완료되었습니다. 로그인 페이지로 이동합니다.';setTimeout(()=>location.href='login.html',900)}else{const remember=form.querySelector('input[type="checkbox"]')?.checked;saveAuthToken(result.token,remember);localStorage.setItem('blog-auth-user',JSON.stringify(result.user));status.textContent=`${result.user.nickname}님, 환영합니다. 잠시 후 이동합니다.`;setTimeout(()=>location.href='profile.html',800)}}catch(error){status.textContent=error.message||'인증 서버 오류가 발생했습니다.'}finally{button.disabled=false}}));

async function syncAuthHeader(){const token=authToken(),loginLink=document.querySelector('.header-login');if(!token||!loginLink)return;try{const result=await authRequest('session',{token});if(!result.success)throw new Error();loginLink.textContent='로그아웃';loginLink.href='#';loginLink.title=`${result.user.nickname}님으로 로그인 중`;loginLink.addEventListener('click',async e=>{e.preventDefault();loginLink.textContent='처리 중';try{await authRequest('logout',{token})}finally{clearAuthToken();location.href='index.html'}})}catch(error){clearAuthToken()}}
syncAuthHeader();

const filters=document.querySelectorAll('.filter-button'),cards=document.querySelectorAll('[data-category]'),search=document.querySelector('#post-search');
function filterPosts(category='전체',query=''){cards.forEach(card=>{const categoryMatch=category==='전체'||card.dataset.category===category;const textMatch=card.textContent.toLowerCase().includes(query.toLowerCase());card.classList.toggle('hidden',!categoryMatch||!textMatch)})}
filters.forEach(btn=>btn.addEventListener('click',()=>{filters.forEach(b=>b.classList.remove('active'));btn.classList.add('active');filterPosts(btn.dataset.filter,search?.value||'')}));
search?.addEventListener('input',()=>filterPosts(document.querySelector('.filter-button.active')?.dataset.filter||'전체',search.value));

const editor=document.querySelector('#editor-body');document.querySelectorAll('[data-insert]').forEach(btn=>btn.addEventListener('click',()=>{if(!editor)return;const [start,end]=[editor.selectionStart,editor.selectionEnd],mark=btn.dataset.insert,selected=editor.value.slice(start,end)||'텍스트';editor.setRangeText(`${mark}${selected}${mark}`,start,end,'select');editor.focus()}));
document.querySelector('#draft-button')?.addEventListener('click',()=>{const status=document.querySelector('.form-status');localStorage.setItem('blog-draft',JSON.stringify({title:document.querySelector('#post-title')?.value,body:editor?.value}));if(status)status.textContent='임시저장했습니다.'});
